<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
Schema::create('tenants', function(Blueprint $t) { $t->id();
$t->string('name');
$t->string('code');
$t->string('domain')->nullable();
$t->json('config')->nullable();
$t->string('status')->default('active');
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('user_profiles', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->unsignedBigInteger('user_id')->nullable();
$t->string('username')->nullable();
$t->string('full_name')->nullable();
$t->string('phone')->nullable();
$t->boolean('is_active')->default(true);
$t->timestamp('last_login_at')->nullable();
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('faculties', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->string('code');
$t->string('name');
$t->unsignedBigInteger('dean_id')->nullable();
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('departments', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->unsignedBigInteger('faculty_id')->nullable();
$t->string('code');
$t->string('name');
$t->unsignedBigInteger('head_of_dept_id')->nullable();
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('study_programs', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->unsignedBigInteger('department_id')->nullable();
$t->string('code');
$t->string('name');
$t->string('level')->nullable();
$t->string('accreditation')->nullable();
$t->unsignedBigInteger('head_of_program_id')->nullable();
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('lecturers', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->unsignedBigInteger('user_id')->nullable();
$t->unsignedBigInteger('study_program_id')->nullable();
$t->string('nidn');
$t->text('specialization')->nullable();
$t->string('academic_rank')->nullable();
$t->date('join_date')->nullable();
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('students', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->unsignedBigInteger('user_id')->nullable();
$t->unsignedBigInteger('study_program_id')->nullable();
$t->string('nim');
$t->integer('entry_year');
$t->unsignedTinyInteger('entry_semester')->nullable();
$t->string('admission_type')->nullable();
$t->text('address')->nullable();
$t->string('phone')->nullable();
$t->string('status')->default('active');
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('courses', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->string('code');
$t->string('name');
$t->unsignedTinyInteger('credits');
$t->unsignedTinyInteger('theory_credits')->default(0);
$t->unsignedTinyInteger('practice_credits')->default(0);
$t->text('description')->nullable();
$t->string('course_type')->nullable();
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('course_prerequisites', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('course_id')->nullable();
$t->unsignedBigInteger('prerequisite_course_id')->nullable();
$t->boolean('is_mandatory')->default(true);
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('academic_years', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->string('year_code');
$t->date('start_date');
$t->date('end_date');
$t->boolean('is_active')->default(false);
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('semesters', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->unsignedBigInteger('academic_year_id')->nullable();
$t->string('semester_type');
$t->date('start_date');
$t->date('end_date');
$t->date('krs_start_date')->nullable();
$t->date('krs_end_date')->nullable();
$t->date('exam_start_date')->nullable();
$t->date('exam_end_date')->nullable();
$t->boolean('is_active')->default(false);
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('curriculums', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->unsignedBigInteger('study_program_id')->nullable();
$t->string('name');
$t->unsignedSmallInteger('year');
$t->text('description')->nullable();
$t->string('status')->default('draft');
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('curriculum_courses', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('curriculum_id')->nullable();
$t->unsignedBigInteger('course_id')->nullable();
$t->unsignedTinyInteger('semester');
$t->boolean('is_mandatory')->default(true);
$t->string('concentration')->nullable();
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('curriculum_templates', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('curriculum_id')->nullable();
$t->unsignedSmallInteger('entry_year');
$t->unsignedTinyInteger('max_sks_per_semester')->default(24);
$t->unsignedTinyInteger('min_sks_per_semester')->default(12);
$t->unsignedSmallInteger('total_credits_required');
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('course_classes', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->unsignedBigInteger('course_id')->nullable();
$t->unsignedBigInteger('semester_id')->nullable();
$t->string('class_code');
$t->unsignedBigInteger('lecturer_id')->nullable();
$t->unsignedBigInteger('co_lecturer_id')->nullable();
$t->unsignedInteger('capacity')->default(40);
$t->string('status')->default('planned');
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('academic_advisors', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->unsignedBigInteger('lecturer_id')->nullable();
$t->unsignedBigInteger('student_id')->nullable();
$t->unsignedBigInteger('semester_id')->nullable();
$t->boolean('is_active')->default(true);
$t->date('assigned_date')->nullable();
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('course_equivalencies', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->unsignedBigInteger('student_id')->nullable();
$t->unsignedBigInteger('original_course_id')->nullable();
$t->unsignedBigInteger('equivalent_course_id')->nullable();
$t->text('reason')->nullable();
$t->unsignedBigInteger('approved_by')->nullable();
$t->timestamp('approved_at')->nullable();
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('krs_headers', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->unsignedBigInteger('student_id')->nullable();
$t->unsignedBigInteger('semester_id')->nullable();
$t->unsignedTinyInteger('total_credits')->default(0);
$t->string('status')->default('draft');
$t->timestamp('submitted_at')->nullable();
$t->timestamp('advisor_approved_at')->nullable();
$t->unsignedBigInteger('approved_by')->nullable();
$t->text('notes')->nullable();
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('krs_details', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('krs_header_id')->nullable();
$t->unsignedBigInteger('course_class_id')->nullable();
$t->string('status')->default('registered');
$t->timestamp('registered_at')->nullable();
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('krs_logs', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('krs_header_id')->nullable();
$t->string('previous_status')->nullable();
$t->string('new_status')->nullable();
$t->unsignedBigInteger('changed_by')->nullable();
$t->timestamp('changed_at')->nullable();
$t->text('reason')->nullable();
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('rooms', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->string('code');
$t->string('name');
$t->string('building')->nullable();
$t->unsignedTinyInteger('floor')->nullable();
$t->unsignedInteger('capacity')->default(40);
$t->boolean('is_active')->default(true);
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('schedules', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->unsignedBigInteger('course_class_id')->nullable();
$t->unsignedTinyInteger('day_of_week');
$t->time('start_time');
$t->time('end_time');
$t->unsignedBigInteger('room_id')->nullable();
$t->unsignedBigInteger('lecturer_id')->nullable();
$t->unsignedTinyInteger('week_number')->nullable();
$t->boolean('is_online')->default(false);
$t->string('meeting_url')->nullable();
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('attendance_sessions', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->unsignedBigInteger('course_class_id')->nullable();
$t->date('meeting_date');
$t->unsignedTinyInteger('meeting_number');
$t->string('topic')->nullable();
$t->timestamp('opened_at')->nullable();
$t->timestamp('closed_at')->nullable();
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('attendance_records', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('attendance_session_id')->nullable();
$t->unsignedBigInteger('student_id')->nullable();
$t->string('status')->default('present');
$t->timestamp('check_in_at')->nullable();
$t->text('notes')->nullable();
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('attendance_corrections', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->unsignedBigInteger('attendance_record_id')->nullable();
$t->unsignedBigInteger('requested_by')->nullable();
$t->text('reason');
$t->string('status')->default('pending');
$t->unsignedBigInteger('approved_by')->nullable();
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('assessments', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->unsignedBigInteger('course_class_id')->nullable();
$t->string('name');
$t->decimal('weight', 5, 2);
$t->decimal('max_score', 5, 2)->default(100);
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('student_grades', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->unsignedBigInteger('course_class_id')->nullable();
$t->unsignedBigInteger('student_id')->nullable();
$t->unsignedBigInteger('assessment_id')->nullable();
$t->decimal('score', 5, 2)->nullable();
$t->string('letter_grade')->nullable();
$t->unsignedBigInteger('graded_by')->nullable();
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('grade_submissions', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->unsignedBigInteger('course_class_id')->nullable();
$t->unsignedBigInteger('submitted_by')->nullable();
$t->string('status')->default('draft');
$t->timestamp('submitted_at')->nullable();
$t->unsignedBigInteger('approved_by')->nullable();
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('leave_requests', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->unsignedBigInteger('student_id')->nullable();
$t->unsignedBigInteger('semester_id')->nullable();
$t->unsignedBigInteger('start_semester_id')->nullable();
$t->unsignedBigInteger('end_semester_id')->nullable();
$t->text('reason');
$t->string('status')->default('pending');
$t->unsignedBigInteger('approved_by')->nullable();
$t->timestamp('approved_at')->nullable();
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('transfers', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->unsignedBigInteger('student_id')->nullable();
$t->unsignedBigInteger('from_study_program_id')->nullable();
$t->unsignedBigInteger('to_study_program_id')->nullable();
$t->date('request_date')->nullable();
$t->string('status')->default('pending');
$t->unsignedBigInteger('approved_by')->nullable();
$t->timestamp('approved_at')->nullable();
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('mbkm_activities', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->unsignedBigInteger('student_id')->nullable();
$t->string('activity_type');
$t->string('institution_name')->nullable();
$t->date('start_date')->nullable();
$t->date('end_date')->nullable();
$t->unsignedTinyInteger('credits_recognized')->nullable();
$t->unsignedBigInteger('recognition_course_id')->nullable();
$t->string('status')->default('pending');
$t->unsignedBigInteger('supervisor_id')->nullable();
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('theses', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->unsignedBigInteger('student_id')->nullable();
$t->string('title');
$t->text('abstract')->nullable();
$t->string('thesis_type')->nullable();
$t->unsignedBigInteger('supervisor_1_id')->nullable();
$t->unsignedBigInteger('supervisor_2_id')->nullable();
$t->date('proposed_date')->nullable();
$t->string('status')->default('proposed');
$t->string('final_document_url')->nullable();
$t->timestamp('defense_date')->nullable();
$t->string('defense_room')->nullable();
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('supervisions', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->unsignedBigInteger('thesis_id')->nullable();
$t->unsignedBigInteger('supervisor_id')->nullable();
$t->timestamp('meeting_date');
$t->string('meeting_type')->nullable();
$t->text('notes')->nullable();
$t->string('status')->default('conducted');
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('thesis_grades', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->unsignedBigInteger('thesis_id')->nullable();
$t->string('component');
$t->decimal('score', 5, 2)->nullable();
$t->string('letter_grade')->nullable();
$t->unsignedBigInteger('grade_by')->nullable();
$t->timestamp('grade_date')->nullable();
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('graduations', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->unsignedBigInteger('student_id')->nullable();
$t->unsignedBigInteger('semester_id')->nullable();
$t->date('graduation_date');
$t->string('degree')->nullable();
$t->decimal('gpa_final', 5, 2)->nullable();
$t->string('status')->default('proposed');
$t->string('decree_number')->nullable();
$t->date('decree_date')->nullable();
$t->unsignedBigInteger('approved_by')->nullable();
$t->timestamp('approved_at')->nullable();
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('graduation_ceremonies', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->string('name');
$t->date('ceremony_date');
$t->string('location')->nullable();
$t->unsignedInteger('quota')->nullable();
$t->boolean('is_active')->default(false);
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('ceremony_registrations', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->unsignedBigInteger('student_id')->nullable();
$t->unsignedBigInteger('graduation_id')->nullable();
$t->unsignedBigInteger('ceremony_id')->nullable();
$t->date('registration_date')->nullable();
$t->string('payment_status')->default('pending');
$t->string('confirmation_status')->default('pending');
$t->string('gown_size')->nullable();
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('pddikti_sync_logs', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->string('entity_type');
$t->string('entity_id');
$t->string('operation');
$t->json('payload')->nullable();
$t->integer('response_code')->nullable();
$t->text('response_message')->nullable();
$t->string('status')->default('pending');
$t->unsignedTinyInteger('retry_count')->default(0);
$t->timestamp('synced_at')->nullable();
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('report_definitions', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->string('name');
$t->string('category')->nullable();
$t->text('query_template')->nullable();
$t->json('parameters')->nullable();
$t->unsignedBigInteger('created_by')->nullable();
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
Schema::create('generated_reports', function(Blueprint $t) { $t->id();
$t->unsignedBigInteger('tenant_id')->nullable();
$t->unsignedBigInteger('report_definition_id')->nullable();
$t->string('file_url')->nullable();
$t->string('file_format')->nullable();
$t->json('parameters_used')->nullable();
$t->timestamp('generated_at')->nullable();
$t->unsignedBigInteger('generated_by')->nullable();
$t->timestamp('expiry_date')->nullable();
$t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
} public function down(): void {
Schema::dropIfExists('generated_reports');
Schema::dropIfExists('report_definitions');
Schema::dropIfExists('pddikti_sync_logs');
Schema::dropIfExists('ceremony_registrations');
Schema::dropIfExists('graduation_ceremonies');
Schema::dropIfExists('graduations');
Schema::dropIfExists('thesis_grades');
Schema::dropIfExists('supervisions');
Schema::dropIfExists('theses');
Schema::dropIfExists('mbkm_activities');
Schema::dropIfExists('transfers');
Schema::dropIfExists('leave_requests');
Schema::dropIfExists('grade_submissions');
Schema::dropIfExists('student_grades');
Schema::dropIfExists('assessments');
Schema::dropIfExists('attendance_corrections');
Schema::dropIfExists('attendance_records');
Schema::dropIfExists('attendance_sessions');
Schema::dropIfExists('schedules');
Schema::dropIfExists('rooms');
Schema::dropIfExists('krs_logs');
Schema::dropIfExists('krs_details');
Schema::dropIfExists('krs_headers');
Schema::dropIfExists('course_equivalencies');
Schema::dropIfExists('academic_advisors');
Schema::dropIfExists('course_classes');
Schema::dropIfExists('curriculum_templates');
Schema::dropIfExists('curriculum_courses');
Schema::dropIfExists('curriculums');
Schema::dropIfExists('semesters');
Schema::dropIfExists('academic_years');
Schema::dropIfExists('course_prerequisites');
Schema::dropIfExists('courses');
Schema::dropIfExists('students');
Schema::dropIfExists('lecturers');
Schema::dropIfExists('study_programs');
Schema::dropIfExists('departments');
Schema::dropIfExists('faculties');
Schema::dropIfExists('user_profiles');
Schema::dropIfExists('tenants');
} };
