<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
 Schema::create('admission_periods', function(Blueprint $t){$t->id();$t->unsignedBigInteger('tenant_id');$t->string('code',50);$t->string('name');$t->date('registration_start');$t->date('registration_end');$t->date('selection_end')->nullable();$t->string('status',20)->default('draft');$t->json('requirements')->nullable();$t->timestamps();$t->softDeletes();$t->unique(['tenant_id','code']);});
 Schema::create('applicants', function(Blueprint $t){$t->id();$t->unsignedBigInteger('tenant_id');$t->unsignedBigInteger('admission_period_id');$t->string('registration_number',80);$t->string('full_name');$t->string('email');$t->string('phone',30)->nullable();$t->string('identity_number',50)->nullable();$t->string('school_origin')->nullable();$t->decimal('selection_score',8,2)->nullable();$t->string('status',30)->default('draft');$t->timestamp('submitted_at')->nullable();$t->timestamps();$t->softDeletes();$t->unique('registration_number');});
 Schema::create('admission_selections', function(Blueprint $t){$t->id();$t->unsignedBigInteger('tenant_id');$t->unsignedBigInteger('applicant_id');$t->unsignedBigInteger('study_program_id');$t->unsignedTinyInteger('choice_order');$t->string('status',20)->default('pending');$t->decimal('score',8,2)->nullable();$t->timestamps();$t->unique(['applicant_id','choice_order']);});
 Schema::create('admission_documents', function(Blueprint $t){$t->id();$t->unsignedBigInteger('tenant_id');$t->unsignedBigInteger('applicant_id');$t->string('document_type',50);$t->string('file_url',500);$t->string('verification_status',20)->default('pending');$t->unsignedBigInteger('verified_by')->nullable();$t->timestamp('verified_at')->nullable();$t->timestamps();});
 Schema::create('teaching_assignments', function(Blueprint $t){$t->id();$t->unsignedBigInteger('tenant_id');$t->unsignedBigInteger('course_class_id');$t->unsignedBigInteger('lecturer_id');$t->string('role',20)->default('primary');$t->unsignedTinyInteger('teaching_load')->default(1);$t->string('status',20)->default('active');$t->timestamps();$t->unique(['course_class_id','lecturer_id']);});
 Schema::table('student_grades', function(Blueprint $t){$t->decimal('uts_score',5,2)->nullable()->after('score');$t->decimal('uas_score',5,2)->nullable()->after('uts_score');$t->decimal('assignment_score',5,2)->nullable()->after('uas_score');$t->decimal('final_score',5,2)->nullable()->after('assignment_score');$t->string('grade_status',20)->default('draft')->after('letter_grade');$t->timestamp('published_at')->nullable()->after('graded_by');});
 } public function down(): void {Schema::table('student_grades',function(Blueprint $t){$t->dropColumn(['uts_score','uas_score','assignment_score','final_score','grade_status','published_at']);});Schema::dropIfExists('teaching_assignments');Schema::dropIfExists('admission_documents');Schema::dropIfExists('admission_selections');Schema::dropIfExists('applicants');Schema::dropIfExists('admission_periods');} };
