<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
 Schema::table('applicants',function(Blueprint $t){$t->unsignedBigInteger('student_id')->nullable()->after('status');$t->timestamp('converted_at')->nullable();$t->index(['tenant_id','status']);});
 Schema::create('admission_bills',function(Blueprint $t){$t->id();$t->unsignedBigInteger('tenant_id');$t->unsignedBigInteger('applicant_id');$t->unsignedBigInteger('fee_type_id')->nullable();$t->string('bill_number',80);$t->string('purpose',40)->default('registration');$t->timestamp('issued_at');$t->date('due_date');$t->decimal('amount',15,2);$t->decimal('paid_amount',15,2)->default(0);$t->string('status',20)->default('unpaid');$t->json('metadata')->nullable();$t->timestamps();$t->softDeletes();$t->unique('bill_number');$t->unique(['applicant_id','purpose']);$t->index(['tenant_id','status']);});
 Schema::create('admission_payments',function(Blueprint $t){$t->id();$t->unsignedBigInteger('tenant_id');$t->unsignedBigInteger('admission_bill_id');$t->unsignedBigInteger('applicant_id');$t->string('payment_number',80);$t->decimal('amount',15,2);$t->string('method',30);$t->string('status',20)->default('confirmed');$t->string('reference',150)->nullable();$t->timestamp('paid_at');$t->unsignedBigInteger('received_by')->nullable();$t->timestamps();$t->softDeletes();$t->unique('payment_number');$t->index(['tenant_id','applicant_id']);});
 Schema::table('admission_bills',function(Blueprint $t){$t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete();$t->foreign('applicant_id')->references('id')->on('applicants')->cascadeOnDelete();$t->foreign('fee_type_id')->references('id')->on('fee_types')->nullOnDelete();});
 Schema::table('admission_payments',function(Blueprint $t){$t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete();$t->foreign('admission_bill_id')->references('id')->on('admission_bills')->cascadeOnDelete();$t->foreign('applicant_id')->references('id')->on('applicants')->cascadeOnDelete();});
 } public function down(): void {Schema::dropIfExists('admission_payments');Schema::dropIfExists('admission_bills');Schema::table('applicants',function(Blueprint $t){$t->dropColumn(['student_id','converted_at']);});} };
