<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
 Schema::table('assessments', function(Blueprint $t){$t->boolean('is_published')->default(false)->after('weight');});
 Schema::table('student_grades', function(Blueprint $t){$t->decimal('grade_point',4,2)->nullable()->after('letter_grade');$t->timestamp('locked_at')->nullable()->after('published_at');});
 Schema::create('academic_transcripts', function(Blueprint $t){$t->id();$t->unsignedBigInteger('tenant_id');$t->unsignedBigInteger('student_id');$t->string('type',20)->default('khs');$t->unsignedBigInteger('semester_id')->nullable();$t->decimal('total_credits',8,2)->default(0);$t->decimal('total_quality_points',10,2)->default(0);$t->decimal('gpa',4,2)->default(0);$t->string('status',20)->default('draft');$t->timestamp('generated_at')->nullable();$t->timestamps();$t->softDeletes();$t->index(['tenant_id','student_id','type']);});
 Schema::create('academic_transcript_items', function(Blueprint $t){$t->id();$t->unsignedBigInteger('tenant_id');$t->unsignedBigInteger('transcript_id');$t->unsignedBigInteger('student_grade_id');$t->unsignedBigInteger('course_id');$t->string('course_code',50);$t->string('course_name');$t->unsignedTinyInteger('credits');$t->decimal('score',5,2)->nullable();$t->string('letter_grade',5)->nullable();$t->decimal('grade_point',4,2)->nullable();$t->decimal('quality_points',8,2)->default(0);$t->timestamps();$t->index(['tenant_id','transcript_id']);});
 Schema::table('academic_transcripts', function(Blueprint $t){$t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete();$t->foreign('student_id')->references('id')->on('students')->restrictOnDelete();$t->foreign('semester_id')->references('id')->on('semesters')->nullOnDelete();});
 Schema::table('academic_transcript_items', function(Blueprint $t){$t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete();$t->foreign('transcript_id')->references('id')->on('academic_transcripts')->cascadeOnDelete();$t->foreign('student_grade_id')->references('id')->on('student_grades')->restrictOnDelete();$t->foreign('course_id')->references('id')->on('courses')->restrictOnDelete();});
 } public function down(): void {Schema::dropIfExists('academic_transcript_items');Schema::dropIfExists('academic_transcripts');Schema::table('student_grades',function(Blueprint $t){$t->dropColumn(['grade_point','locked_at']);});Schema::table('assessments',function(Blueprint $t){$t->dropColumn(['is_published']);});} };
