from pathlib import Path
root=Path('/home/ubuntu/siakad-laravel/app/Filament/Resources')
def w(rel,s):
 p=root/rel;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(s.strip()+'\n')
w('Rooms/RoomResource.php',r'''<?php
namespace App\Filament\Resources\Rooms;
use App\Models\Room; use App\Filament\Resources\Rooms\Pages; use Filament\Forms\Components\{Select,TextInput}; use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Support\Icons\Heroicon; use Filament\Tables\{Actions\DeleteAction,Actions\EditAction,Columns\TextColumn,Filters\SelectFilter,Table}; use BackedEnum; use UnitEnum;
class RoomResource extends Resource { protected static ?string $slug='rooms'; protected static ?string $model=Room::class; protected static string|BackedEnum|null $navigationIcon=Heroicon::OutlinedBuildingOffice; protected static string|UnitEnum|null $navigationGroup='Penjadwalan & Ruang'; protected static ?string $navigationLabel='Ruang'; protected static ?string $modelLabel='Ruang'; protected static ?string $pluralModelLabel='Ruang'; public static function form(Schema $schema):Schema{return $schema->components([TextInput::make('code')->label('Kode Ruang')->required()->unique(ignoreRecord:true)->maxLength(30),TextInput::make('name')->label('Nama Ruang')->required()->maxLength(100),TextInput::make('building')->label('Gedung')->maxLength(100),TextInput::make('floor')->label('Lantai')->numeric()->minValue(1),TextInput::make('capacity')->label('Kapasitas')->numeric()->minValue(1)->required(),Select::make('is_active')->label('Status')->options([1=>'Aktif',0=>'Tidak Aktif'])->default(1)->required()]);} public static function table(Table $table):Table{return $table->columns([TextColumn::make('code')->label('Kode')->searchable()->sortable(),TextColumn::make('name')->label('Nama Ruang')->searchable(),TextColumn::make('building')->label('Gedung'),TextColumn::make('floor')->label('Lantai'),TextColumn::make('capacity')->label('Kapasitas')->sortable(),TextColumn::make('is_active')->label('Status')->formatStateUsing(fn($state)=>$state?'Aktif':'Tidak Aktif')->badge()])->filters([SelectFilter::make('is_active')->label('Status')->options([1=>'Aktif',0=>'Tidak Aktif'])])->actions([EditAction::make()->label('Ubah'),DeleteAction::make()->label('Hapus')->requiresConfirmation()]);} public static function getPages():array{return ['index'=>Pages\ListRooms::route('/'),'create'=>Pages\CreateRoom::route('/create'),'edit'=>Pages\EditRoom::route('/{record}/edit')];}}
''')
w('CourseClasss/CourseClassResource.php',r'''<?php
namespace App\Filament\Resources\CourseClasss;
use App\Models\CourseClass; use App\Filament\Resources\CourseClasss\Pages; use Filament\Forms\Components\{Select,TextInput}; use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Support\Icons\Heroicon; use Filament\Tables\{Actions\DeleteAction,Actions\EditAction,Columns\TextColumn,Table}; use BackedEnum; use UnitEnum;
class CourseClassResource extends Resource { protected static ?string $slug='course-classes'; protected static ?string $model=CourseClass::class; protected static string|BackedEnum|null $navigationIcon=Heroicon::OutlinedRectangleStack; protected static string|UnitEnum|null $navigationGroup='Penjadwalan & Ruang'; protected static ?string $navigationLabel='Kelas Perkuliahan'; protected static ?string $modelLabel='Kelas Perkuliahan'; protected static ?string $pluralModelLabel='Kelas Perkuliahan'; public static function form(Schema $schema):Schema{return $schema->components([Select::make('course_id')->label('Mata Kuliah')->relationship('course','name')->searchable()->preload()->required(),Select::make('semester_id')->label('Semester')->relationship('semester','id')->searchable()->preload()->required(),TextInput::make('class_code')->label('Kode Kelas')->required()->maxLength(50),Select::make('lecturer_id')->label('Dosen Utama')->relationship('lecturer','nidn')->searchable()->preload()->nullable(),Select::make('co_lecturer_id')->label('Dosen Pendamping')->relationship('coLecturer','nidn')->searchable()->preload()->nullable(),TextInput::make('capacity')->label('Kapasitas')->numeric()->minValue(1)->required()->default(40),Select::make('status')->label('Status')->options(['planned'=>'Direncanakan','active'=>'Aktif','closed'=>'Ditutup'])->default('planned')->required()]);} public static function table(Table $table):Table{return $table->columns([TextColumn::make('class_code')->label('Kelas')->searchable(),TextColumn::make('course.code')->label('Kode Mata Kuliah'),TextColumn::make('course.name')->label('Mata Kuliah'),TextColumn::make('semester.id')->label('Semester'),TextColumn::make('capacity')->label('Kapasitas'),TextColumn::make('status')->label('Status')->badge()])->actions([EditAction::make()->label('Ubah')->visible(fn(CourseClass $r)=>$r->status!=='closed'),DeleteAction::make()->label('Hapus')->visible(fn(CourseClass $r)=>$r->status==='planned')->requiresConfirmation()]);} public static function getPages():array{return ['index'=>Pages\ListCourseClasss::route('/'),'create'=>Pages\CreateCourseClass::route('/create'),'edit'=>Pages\EditCourseClass::route('/{record}/edit')];}}
''')
w('Schedules/ScheduleResource.php',r'''<?php
namespace App\Filament\Resources\Schedules;
use App\Models\Schedule; use App\Filament\Resources\Schedules\Pages; use Filament\Forms\Components\{Select,TextInput,TimePicker,Toggle}; use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Support\Icons\Heroicon; use Filament\Tables\{Actions\DeleteAction,Actions\EditAction,Columns\TextColumn,Table}; use BackedEnum; use UnitEnum;
class ScheduleResource extends Resource { protected static ?string $slug='schedules'; protected static ?string $model=Schedule::class; protected static string|BackedEnum|null $navigationIcon=Heroicon::OutlinedCalendarDays; protected static string|UnitEnum|null $navigationGroup='Penjadwalan & Ruang'; protected static ?string $navigationLabel='Jadwal'; protected static ?string $modelLabel='Jadwal'; protected static ?string $pluralModelLabel='Jadwal'; public static function form(Schema $schema):Schema{return $schema->components([Select::make('course_class_id')->label('Kelas Perkuliahan')->relationship('courseClass','class_code')->searchable()->preload()->required(),Select::make('day_of_week')->label('Hari')->options([1=>'Senin',2=>'Selasa',3=>'Rabu',4=>'Kamis',5=>'Jumat',6=>'Sabtu',7=>'Minggu'])->required(),TimePicker::make('start_time')->label('Mulai')->seconds(false)->required(),TimePicker::make('end_time')->label('Selesai')->seconds(false)->after('start_time')->required(),Select::make('room_id')->label('Ruang')->relationship('room','name')->searchable()->preload()->nullable(),Select::make('lecturer_id')->label('Dosen')->relationship('lecturer','nidn')->searchable()->preload()->nullable(),TextInput::make('week_number')->label('Minggu Ke-')->numeric()->minValue(1)->maxValue(52),Toggle::make('is_online')->label('Perkuliahan Daring')->default(false),TextInput::make('meeting_url')->label('URL Pertemuan')->url()->nullable()]);} public static function table(Table $table):Table{return $table->columns([TextColumn::make('courseClass.class_code')->label('Kelas'),TextColumn::make('courseClass.course.name')->label('Mata Kuliah'),TextColumn::make('day_of_week')->label('Hari')->formatStateUsing(fn($s)=>[1=>'Senin',2=>'Selasa',3=>'Rabu',4=>'Kamis',5=>'Jumat',6=>'Sabtu',7=>'Minggu'][$s]??$s),TextColumn::make('start_time')->label('Mulai'),TextColumn::make('end_time')->label('Selesai'),TextColumn::make('room.name')->label('Ruang')->placeholder('Daring'),TextColumn::make('lecturer.nidn')->label('Dosen')])->actions([EditAction::make()->label('Ubah'),DeleteAction::make()->label('Hapus')->requiresConfirmation()]);} public static function getPages():array{return ['index'=>Pages\ListSchedules::route('/'),'create'=>Pages\CreateSchedule::route('/create'),'edit'=>Pages\EditSchedule::route('/{record}/edit')];}}
''')
w('TeachingAssignments/TeachingAssignmentResource.php',r'''<?php
namespace App\Filament\Resources\TeachingAssignments;
use App\Models\TeachingAssignment; use App\Filament\Resources\TeachingAssignments\Pages; use Filament\Forms\Components\{Select,TextInput}; use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Support\Icons\Heroicon; use Filament\Tables\{Actions\DeleteAction,Actions\EditAction,Columns\TextColumn,Table}; use BackedEnum; use UnitEnum;
class TeachingAssignmentResource extends Resource { protected static ?string $slug='teaching-assignments'; protected static ?string $model=TeachingAssignment::class; protected static string|BackedEnum|null $navigationIcon=Heroicon::OutlinedAcademicCap; protected static string|UnitEnum|null $navigationGroup='Penjadwalan & Ruang'; protected static ?string $navigationLabel='Dosen Pengampu'; protected static ?string $modelLabel='Dosen Pengampu'; protected static ?string $pluralModelLabel='Dosen Pengampu'; public static function form(Schema $schema):Schema{return $schema->components([Select::make('course_class_id')->label('Kelas')->relationship('courseClass','class_code')->searchable()->preload()->required(),Select::make('lecturer_id')->label('Dosen')->relationship('lecturer','nidn')->searchable()->preload()->required(),Select::make('role')->label('Peran')->options(['primary'=>'Dosen Utama','co'=>'Co-Dosen'])->default('primary')->required(),TextInput::make('teaching_load')->label('Beban Mengajar')->numeric()->minValue(0)->default(1),Select::make('status')->label('Status')->options(['active'=>'Aktif','inactive'=>'Tidak Aktif'])->default('active')->required()]);} public static function table(Table $table):Table{return $table->columns([TextColumn::make('courseClass.class_code')->label('Kelas'),TextColumn::make('lecturer.user.name')->label('Dosen'),TextColumn::make('role')->label('Peran')->badge(),TextColumn::make('teaching_load')->label('Beban'),TextColumn::make('status')->label('Status')->badge()])->actions([EditAction::make()->label('Ubah'),DeleteAction::make()->label('Hapus')->requiresConfirmation()]);} public static function getPages():array{return ['index'=>Pages\ListTeachingAssignments::route('/'),'create'=>Pages\CreateTeachingAssignment::route('/create'),'edit'=>Pages\EditTeachingAssignment::route('/{record}/edit')];}}
''')
print('generated')
