from pathlib import Path
root=Path('/home/ubuntu/siakad-laravel/app/Filament/Resources')
def write(rel,text):
 p=root/rel; p.parent.mkdir(parents=True,exist_ok=True); p.write_text(text.strip()+'\n')
write('Curriculums/CurriculumResource.php',r'''<?php
namespace App\Filament\Resources\Curriculums;
use App\Models\Curriculum;
use App\Filament\Resources\Curriculums\Pages;
use Filament\Forms\Components\{Select, TextInput, Textarea};
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Support\Icons\Heroicon;
use Filament\Tables\{Actions\DeleteAction, Actions\EditAction, Columns\TextColumn, Filters\SelectFilter, Table};
use BackedEnum; use UnitEnum;
class CurriculumResource extends Resource
{
 protected static ?string $model=Curriculum::class; protected static string|BackedEnum|null $navigationIcon=Heroicon::OutlinedBookOpen; protected static string|UnitEnum|null $navigationGroup='Kurikulum & Mata Kuliah'; protected static ?string $navigationLabel='Kurikulum'; protected static ?string $modelLabel='Kurikulum'; protected static ?string $pluralModelLabel='Kurikulum';
 public static function form(Schema $schema): Schema { return $schema->components([Select::make('study_program_id')->label('Program Studi')->relationship('studyProgram','name')->searchable()->preload()->required(), TextInput::make('name')->label('Nama Kurikulum')->required()->maxLength(255), TextInput::make('year')->label('Tahun Kurikulum')->numeric()->minValue(1900)->maxValue((int)date('Y')+5)->required(), Select::make('status')->label('Status')->options(['draft'=>'Draf','active'=>'Aktif','archived'=>'Diarsipkan'])->default('draft')->required(), Textarea::make('description')->label('Deskripsi')->columnSpanFull()]); }
 public static function table(Table $table): Table { return $table->columns([TextColumn::make('name')->label('Nama Kurikulum')->searchable()->sortable(),TextColumn::make('studyProgram.name')->label('Program Studi')->searchable(),TextColumn::make('year')->label('Tahun')->sortable(),TextColumn::make('status')->label('Status')->badge(),TextColumn::make('courses_count')->label('Jumlah Mata Kuliah')->counts('courses')])->filters([SelectFilter::make('status')->label('Status')->options(['draft'=>'Draf','active'=>'Aktif','archived'=>'Diarsipkan'])])->actions([EditAction::make()->label('Ubah'),DeleteAction::make()->label('Hapus')->requiresConfirmation()])->defaultSort('year','desc'); }
 public static function getRelations(): array { return [\App\Filament\Resources\Curriculums\RelationManagers\CoursesRelationManager::class]; }
 public static function getPages(): array { return ['index'=>Pages\ListCurriculums::route('/'),'create'=>Pages\CreateCurriculum::route('/create'),'edit'=>Pages\EditCurriculum::route('/{record}/edit')]; }
}
''')
write('CurriculumCourses/CurriculumCourseResource.php',r'''<?php
namespace App\Filament\Resources\CurriculumCourses;
use App\Models\CurriculumCourse; use App\Filament\Resources\CurriculumCourses\Pages;
use Filament\Forms\Components\{Select, TextInput}; use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Support\Icons\Heroicon; use Filament\Tables\{Actions\DeleteAction,Actions\EditAction,Columns\TextColumn,Table}; use BackedEnum; use UnitEnum;
class CurriculumCourseResource extends Resource { protected static ?string $model=CurriculumCourse::class; protected static string|BackedEnum|null $navigationIcon=Heroicon::OutlinedListBullet; protected static string|UnitEnum|null $navigationGroup='Kurikulum & Mata Kuliah'; protected static ?string $navigationLabel='Mata Kuliah dalam Kurikulum'; protected static ?string $modelLabel='Mata Kuliah dalam Kurikulum'; protected static ?string $pluralModelLabel='Mata Kuliah dalam Kurikulum'; public static function form(Schema $schema):Schema{return $schema->components([Select::make('curriculum_id')->label('Kurikulum')->relationship('curriculum','name')->searchable()->preload()->required(),Select::make('course_id')->label('Mata Kuliah')->relationship('course','name')->searchable()->preload()->required(),TextInput::make('semester')->label('Semester')->numeric()->minValue(1)->maxValue(14)->required(),Select::make('is_mandatory')->label('Sifat Mata Kuliah')->options([1=>'Wajib',0=>'Pilihan'])->default(1)->required(),TextInput::make('concentration')->label('Konsentrasi')->maxLength(100)]);} public static function table(Table $table):Table{return $table->columns([TextColumn::make('curriculum.name')->label('Kurikulum')->searchable(),TextColumn::make('course.code')->label('Kode')->searchable(),TextColumn::make('course.name')->label('Mata Kuliah')->searchable(),TextColumn::make('semester')->label('Semester')->sortable(),TextColumn::make('is_mandatory')->label('Sifat')->formatStateUsing(fn($state)=>$state?'Wajib':'Pilihan')->badge(),TextColumn::make('concentration')->label('Konsentrasi')])->actions([EditAction::make()->label('Ubah'),DeleteAction::make()->label('Hapus')->requiresConfirmation()])->defaultSort('semester');} public static function getPages():array{return ['index'=>Pages\ListCurriculumCourses::route('/'),'create'=>Pages\CreateCurriculumCourse::route('/create'),'edit'=>Pages\EditCurriculumCourse::route('/{record}/edit')];}}
''')
write('CurriculumTemplates/CurriculumTemplateResource.php',r'''<?php
namespace App\Filament\Resources\CurriculumTemplates;
use App\Models\CurriculumTemplate; use App\Filament\Resources\CurriculumTemplates\Pages; use Filament\Forms\Components\{Select,TextInput}; use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Support\Icons\Heroicon; use Filament\Tables\{Actions\DeleteAction,Actions\EditAction,Columns\TextColumn,Table}; use BackedEnum; use UnitEnum;
class CurriculumTemplateResource extends Resource { protected static ?string $model=CurriculumTemplate::class; protected static string|BackedEnum|null $navigationIcon=Heroicon::OutlinedDocumentDuplicate; protected static string|UnitEnum|null $navigationGroup='Kurikulum & Mata Kuliah'; protected static ?string $navigationLabel='Template Kurikulum'; protected static ?string $modelLabel='Template Kurikulum'; protected static ?string $pluralModelLabel='Template Kurikulum'; public static function form(Schema $schema):Schema{return $schema->components([Select::make('curriculum_id')->label('Kurikulum')->relationship('curriculum','name')->searchable()->preload()->required(),TextInput::make('entry_year')->label('Tahun Masuk')->numeric()->minValue(1900)->maxValue((int)date('Y')+5)->required(),TextInput::make('max_sks_per_semester')->label('Maksimal SKS per Semester')->numeric()->minValue(1)->maxValue(40)->default(24)->required(),TextInput::make('min_sks_per_semester')->label('Minimal SKS per Semester')->numeric()->minValue(0)->maxValue(40)->default(12)->required()->lte('max_sks_per_semester'),TextInput::make('total_credits_required')->label('Total SKS Kelulusan')->numeric()->minValue(1)->maxValue(300)->required()]);} public static function table(Table $table):Table{return $table->columns([TextColumn::make('curriculum.name')->label('Kurikulum')->searchable(),TextColumn::make('entry_year')->label('Tahun Masuk'),TextColumn::make('min_sks_per_semester')->label('Minimal SKS'),TextColumn::make('max_sks_per_semester')->label('Maksimal SKS'),TextColumn::make('total_credits_required')->label('Total SKS Kelulusan')])->actions([EditAction::make()->label('Ubah'),DeleteAction::make()->label('Hapus')->requiresConfirmation()]);} public static function getPages():array{return ['index'=>Pages\ListCurriculumTemplates::route('/'),'create'=>Pages\CreateCurriculumTemplate::route('/create'),'edit'=>Pages\EditCurriculumTemplate::route('/{record}/edit')];}}
''')
write('CourseEquivalencys/CourseEquivalencyResource.php',r'''<?php
namespace App\Filament\Resources\CourseEquivalencys;
use App\Models\CourseEquivalency; use App\Filament\Resources\CourseEquivalencys\Pages; use Filament\Forms\Components\{Select,Textarea}; use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Support\Icons\Heroicon; use Filament\Tables\{Actions\DeleteAction,Actions\EditAction,Columns\TextColumn,Table}; use BackedEnum; use UnitEnum;
class CourseEquivalencyResource extends Resource { protected static ?string $model=CourseEquivalency::class; protected static string|BackedEnum|null $navigationIcon=Heroicon::OutlinedArrowsRightLeft; protected static string|UnitEnum|null $navigationGroup='Kurikulum & Mata Kuliah'; protected static ?string $navigationLabel='Ekuivalensi Mata Kuliah'; protected static ?string $modelLabel='Ekuivalensi Mata Kuliah'; protected static ?string $pluralModelLabel='Ekuivalensi Mata Kuliah'; public static function form(Schema $schema):Schema{return $schema->components([Select::make('student_id')->label('Mahasiswa')->relationship('student','nim')->searchable()->preload()->required(),Select::make('original_course_id')->label('Mata Kuliah Asal')->relationship('originalCourse','name')->searchable()->preload()->required(),Select::make('equivalent_course_id')->label('Mata Kuliah Pengganti')->relationship('equivalentCourse','name')->searchable()->preload()->required()->different('original_course_id'),Textarea::make('reason')->label('Alasan')->required()->columnSpanFull()]);} public static function table(Table $table):Table{return $table->columns([TextColumn::make('student.nim')->label('NIM')->searchable(),TextColumn::make('originalCourse.code')->label('Kode Asal'),TextColumn::make('originalCourse.name')->label('Mata Kuliah Asal'),TextColumn::make('equivalentCourse.code')->label('Kode Pengganti'),TextColumn::make('approved_at')->label('Disetujui Pada')->dateTime('d M Y H:i')->placeholder('Belum disetujui')])->actions([EditAction::make()->label('Ubah'),DeleteAction::make()->label('Hapus')->requiresConfirmation()]);} public static function getPages():array{return ['index'=>Pages\ListCourseEquivalencys::route('/'),'create'=>Pages\CreateCourseEquivalency::route('/create'),'edit'=>Pages\EditCourseEquivalency::route('/{record}/edit')];}}
''')
write('Curriculums/RelationManagers/CoursesRelationManager.php',r'''<?php
namespace App\Filament\Resources\Curriculums\RelationManagers;
use Filament\Resources\RelationManagers\RelationManager; use Filament\Schemas\Schema; use Filament\Forms\Components\{Select,TextInput}; use Filament\Tables\{Actions\CreateAction,Actions\DeleteAction,Actions\EditAction,Columns\TextColumn,Table};
class CoursesRelationManager extends RelationManager { protected static string $relationship='courses'; protected static ?string $title='Mata Kuliah Kurikulum'; public function form(Schema $schema):Schema{return $schema->components([Select::make('course_id')->label('Mata Kuliah')->relationship('course','name')->searchable()->preload()->required(),TextInput::make('semester')->label('Semester')->numeric()->minValue(1)->maxValue(14)->required(),Select::make('is_mandatory')->label('Sifat')->options([1=>'Wajib',0=>'Pilihan'])->default(1)->required(),TextInput::make('concentration')->label('Konsentrasi')]);} public function table(Table $table):Table{return $table->columns([TextColumn::make('course.code')->label('Kode'),TextColumn::make('course.name')->label('Mata Kuliah'),TextColumn::make('semester')->label('Semester'),TextColumn::make('is_mandatory')->label('Sifat')->formatStateUsing(fn($state)=>$state?'Wajib':'Pilihan')->badge()])->headerActions([CreateAction::make()->label('Tambah Mata Kuliah')])->actions([EditAction::make()->label('Ubah'),DeleteAction::make()->label('Hapus')->requiresConfirmation()]);}}
''')
print('generated')
