from pathlib import Path
root=Path('/home/ubuntu/siakad-laravel/app/Filament/Resources')
def w(rel,s):
 p=root/rel;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(s.strip()+'\n')
common="use Filament\\Resources\\Resource; use Filament\\Schemas\\Schema; use Filament\\Support\\Icons\\Heroicon; use BackedEnum; use UnitEnum;"
w('FeeTypes/FeeTypeResource.php',r'''<?php
namespace App\Filament\Resources\FeeTypes;
use App\Models\FeeType; use App\Filament\Resources\FeeTypes\Pages; use Filament\Forms\Components\{Select,TextInput}; use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Support\Icons\Heroicon; use Filament\Tables\{Actions\DeleteAction,Actions\EditAction,Columns\TextColumn,Table}; use BackedEnum; use UnitEnum;
class FeeTypeResource extends Resource { protected static ?string $slug='fee-types'; protected static ?string $model=FeeType::class; protected static string|BackedEnum|null $navigationIcon=Heroicon::OutlinedBanknotes; protected static string|UnitEnum|null $navigationGroup='Keuangan'; protected static ?string $navigationLabel='Jenis Biaya'; protected static ?string $modelLabel='Jenis Biaya'; protected static ?string $pluralModelLabel='Jenis Biaya'; public static function form(Schema $schema):Schema{return $schema->components([TextInput::make('code')->label('Kode')->required()->maxLength(50)->unique(ignoreRecord:true),TextInput::make('name')->label('Nama Biaya')->required()->maxLength(150),TextInput::make('default_amount')->label('Nominal Default')->numeric()->minValue(0)->required(),Select::make('frequency')->label('Frekuensi')->options(['one_time'=>'Sekali Bayar','per_semester'=>'Per Semester','per_year'=>'Per Tahun'])->default('per_semester')->required(),Select::make('is_active')->label('Status')->options([1=>'Aktif',0=>'Tidak Aktif'])->default(1)->required()]);} public static function table(Table $table):Table{return $table->columns([TextColumn::make('code')->label('Kode')->searchable(),TextColumn::make('name')->label('Nama'),TextColumn::make('default_amount')->label('Nominal')->money('IDR'),TextColumn::make('frequency')->label('Frekuensi')->badge(),TextColumn::make('is_active')->label('Status')->formatStateUsing(fn($s)=>$s?'Aktif':'Tidak Aktif')->badge()])->actions([EditAction::make()->label('Ubah'),DeleteAction::make()->label('Hapus')->requiresConfirmation()]);} public static function getPages():array{return ['index'=>Pages\ListFeeTypes::route('/'),'create'=>Pages\CreateFeeType::route('/create'),'edit'=>Pages\EditFeeType::route('/{record}/edit')];}}
''')
w('AcademicBills/AcademicBillResource.php',r'''<?php
namespace App\Filament\Resources\AcademicBills;
use App\Models\AcademicBill; use App\Filament\Resources\AcademicBills\Pages; use Filament\Forms\Components\{DatePicker,Select,TextInput}; use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Support\Icons\Heroicon; use Filament\Tables\{Actions\DeleteAction,Actions\EditAction,Columns\TextColumn,Table}; use BackedEnum; use UnitEnum;
class AcademicBillResource extends Resource { protected static ?string $slug='academic-bills'; protected static ?string $model=AcademicBill::class; protected static string|BackedEnum|null $navigationIcon=Heroicon::OutlinedDocumentCurrencyDollar; protected static string|UnitEnum|null $navigationGroup='Keuangan'; protected static ?string $navigationLabel='Tagihan Akademik'; protected static ?string $modelLabel='Tagihan Akademik'; protected static ?string $pluralModelLabel='Tagihan Akademik'; public static function form(Schema $schema):Schema{return $schema->components([Select::make('student_id')->label('Mahasiswa')->relationship('student','nim')->searchable()->preload()->required(),Select::make('semester_id')->label('Semester')->relationship('semester','id')->searchable()->preload()->required(),Select::make('fee_type_id')->label('Jenis Biaya')->relationship('feeType','name')->searchable()->preload()->required(),TextInput::make('bill_number')->label('Nomor Tagihan')->required()->maxLength(80),DatePicker::make('issued_at')->label('Tanggal Terbit')->required(),DatePicker::make('due_date')->label('Jatuh Tempo')->afterOrEqual('issued_at')->required(),TextInput::make('subtotal')->label('Subtotal')->numeric()->minValue(0)->required(),TextInput::make('discount')->label('Diskon')->numeric()->minValue(0)->default(0),TextInput::make('penalty')->label('Denda')->numeric()->minValue(0)->default(0),TextInput::make('total')->label('Total')->numeric()->minValue(0)->required(),Select::make('status')->label('Status')->options(['unpaid'=>'Belum Bayar','partial'=>'Sebagian','paid'=>'Lunas','overdue'=>'Jatuh Tempo'])->default('unpaid')->required()]);} public static function table(Table $table):Table{return $table->columns([TextColumn::make('bill_number')->label('Nomor')->searchable(),TextColumn::make('student.nim')->label('NIM'),TextColumn::make('student.user.name')->label('Mahasiswa'),TextColumn::make('feeType.name')->label('Jenis'),TextColumn::make('total')->label('Total')->money('IDR'),TextColumn::make('paid_amount')->label('Terbayar')->money('IDR'),TextColumn::make('status')->label('Status')->badge(),TextColumn::make('due_date')->label('Jatuh Tempo')->date()])->actions([EditAction::make()->label('Ubah')->visible(fn(AcademicBill $r)=>!in_array($r->status,['paid'],true)),DeleteAction::make()->label('Hapus')->visible(fn(AcademicBill $r)=>$r->paid_amount==0)->requiresConfirmation()]);} public static function getPages():array{return ['index'=>Pages\ListAcademicBills::route('/'),'create'=>Pages\CreateAcademicBill::route('/create'),'edit'=>Pages\EditAcademicBill::route('/{record}/edit')];}}
''')
w('Payments/PaymentResource.php',r'''<?php
namespace App\Filament\Resources\Payments;
use App\Models\Payment; use App\Filament\Resources\Payments\Pages; use Filament\Forms\Components\{DateTimePicker,Select,TextInput}; use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Support\Icons\Heroicon; use Filament\Tables\{Actions\DeleteAction,Actions\EditAction,Columns\TextColumn,Table}; use BackedEnum; use UnitEnum;
class PaymentResource extends Resource { protected static ?string $slug='payments'; protected static ?string $model=Payment::class; protected static string|BackedEnum|null $navigationIcon=Heroicon::OutlinedCreditCard; protected static string|UnitEnum|null $navigationGroup='Keuangan'; protected static ?string $navigationLabel='Pembayaran SPP'; protected static ?string $modelLabel='Pembayaran SPP'; protected static ?string $pluralModelLabel='Pembayaran SPP'; public static function form(Schema $schema):Schema{return $schema->components([Select::make('academic_bill_id')->label('Tagihan')->relationship('bill','bill_number')->searchable()->preload()->required(),Select::make('student_id')->label('Mahasiswa')->relationship('student','nim')->searchable()->preload()->required(),TextInput::make('payment_number')->label('Nomor Pembayaran')->required()->maxLength(80),TextInput::make('amount')->label('Nominal')->numeric()->minValue(0.01)->required(),Select::make('method')->label('Metode')->options(['cash'=>'Tunai','transfer'=>'Transfer','virtual_account'=>'Virtual Account','qris'=>'QRIS'])->required(),Select::make('status')->label('Status')->options(['pending'=>'Menunggu','confirmed'=>'Dikonfirmasi','failed'=>'Gagal','void'=>'Dibatalkan'])->default('confirmed')->required(),DateTimePicker::make('paid_at')->label('Dibayar Pada')->required(),TextInput::make('reference')->label('Referensi')->maxLength(150)]);} public static function table(Table $table):Table{return $table->columns([TextColumn::make('payment_number')->label('Nomor')->searchable(),TextColumn::make('bill.bill_number')->label('Tagihan'),TextColumn::make('student.nim')->label('NIM'),TextColumn::make('amount')->label('Nominal')->money('IDR'),TextColumn::make('method')->label('Metode')->badge(),TextColumn::make('status')->label('Status')->badge(),TextColumn::make('paid_at')->label('Waktu')->dateTime('d M Y H:i')])->actions([EditAction::make()->label('Ubah')->visible(fn(Payment $r)=>$r->status==='pending'),DeleteAction::make()->label('Hapus')->visible(fn(Payment $r)=>$r->status==='pending')->requiresConfirmation()]);} public static function getPages():array{return ['index'=>Pages\ListPayments::route('/'),'create'=>Pages\CreatePayment::route('/create'),'edit'=>Pages\EditPayment::route('/{record}/edit')];}}
''')
w('AdmissionPeriods/AdmissionPeriodResource.php',r'''<?php
namespace App\Filament\Resources\AdmissionPeriods;
use App\Models\AdmissionPeriod; use App\Filament\Resources\AdmissionPeriods\Pages; use Filament\Forms\Components\{DatePicker,Select,TextInput,Textarea}; use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Support\Icons\Heroicon; use Filament\Tables\{Actions\DeleteAction,Actions\EditAction,Columns\TextColumn,Table}; use BackedEnum; use UnitEnum;
class AdmissionPeriodResource extends Resource { protected static ?string $slug='admission-periods'; protected static ?string $model=AdmissionPeriod::class; protected static string|BackedEnum|null $navigationIcon=Heroicon::OutlinedCalendarDays; protected static string|UnitEnum|null $navigationGroup='Penerimaan Mahasiswa Baru'; protected static ?string $navigationLabel='Periode PMB'; protected static ?string $modelLabel='Periode PMB'; protected static ?string $pluralModelLabel='Periode PMB'; public static function form(Schema $schema):Schema{return $schema->components([TextInput::make('code')->label('Kode')->required()->maxLength(50)->unique(ignoreRecord:true),TextInput::make('name')->label('Nama Periode')->required()->maxLength(150),DatePicker::make('registration_start')->label('Mulai Pendaftaran')->required(),DatePicker::make('registration_end')->label('Akhir Pendaftaran')->afterOrEqual('registration_start')->required(),DatePicker::make('selection_end')->label('Akhir Seleksi')->afterOrEqual('registration_end'),Select::make('status')->label('Status')->options(['draft'=>'Draf','open'=>'Dibuka','closed'=>'Ditutup'])->default('draft')->required(),Textarea::make('requirements')->label('Persyaratan JSON')->helperText('Isi konfigurasi persyaratan dalam format JSON.')->json()]);} public static function table(Table $table):Table{return $table->columns([TextColumn::make('code')->label('Kode')->searchable(),TextColumn::make('name')->label('Nama'),TextColumn::make('registration_start')->label('Mulai')->date(),TextColumn::make('registration_end')->label('Selesai')->date(),TextColumn::make('status')->label('Status')->badge(),TextColumn::make('applicants_count')->counts('applicants')->label('Pendaftar')])->actions([EditAction::make()->label('Ubah')->visible(fn(AdmissionPeriod $r)=>$r->status!=='closed'),DeleteAction::make()->label('Hapus')->visible(fn(AdmissionPeriod $r)=>$r->status==='draft')->requiresConfirmation()]);} public static function getPages():array{return ['index'=>Pages\ListAdmissionPeriods::route('/'),'create'=>Pages\CreateAdmissionPeriod::route('/create'),'edit'=>Pages\EditAdmissionPeriod::route('/{record}/edit')];}}
''')
w('Applicants/ApplicantResource.php',r'''<?php
namespace App\Filament\Resources\Applicants;
use App\Models\Applicant; use App\Filament\Resources\Applicants\Pages; use Filament\Forms\Components\{DateTimePicker,Select,TextInput}; use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Support\Icons\Heroicon; use Filament\Tables\{Actions\DeleteAction,Actions\EditAction,Columns\TextColumn,Table}; use BackedEnum; use UnitEnum;
class ApplicantResource extends Resource { protected static ?string $slug='applicants'; protected static ?string $model=Applicant::class; protected static string|BackedEnum|null $navigationIcon=Heroicon::OutlinedUserPlus; protected static string|UnitEnum|null $navigationGroup='Penerimaan Mahasiswa Baru'; protected static ?string $navigationLabel='Pendaftar PMB'; protected static ?string $modelLabel='Pendaftar PMB'; protected static ?string $pluralModelLabel='Pendaftar PMB'; public static function form(Schema $schema):Schema{return $schema->components([Select::make('admission_period_id')->label('Periode PMB')->relationship('period','name')->searchable()->preload()->required(),TextInput::make('registration_number')->label('Nomor Pendaftaran')->required()->maxLength(80)->unique(ignoreRecord:true),TextInput::make('full_name')->label('Nama Lengkap')->required()->maxLength(150),TextInput::make('email')->label('Surel')->email()->required(),TextInput::make('phone')->label('Telepon')->maxLength(30),TextInput::make('identity_number')->label('Nomor Identitas')->maxLength(50),TextInput::make('school_origin')->label('Asal Sekolah')->maxLength(150),TextInput::make('selection_score')->label('Nilai Seleksi')->numeric()->minValue(0)->maxValue(100),Select::make('status')->label('Status')->options(['draft'=>'Draf','submitted'=>'Diajukan','under_review'=>'Ditinjau','selection_passed'=>'Lulus Seleksi','selection_failed'=>'Tidak Lulus','converted'=>'Dikonversi'])->default('draft')->required(),DateTimePicker::make('submitted_at')->label('Diajukan Pada')->native(false)]);} public static function table(Table $table):Table{return $table->columns([TextColumn::make('registration_number')->label('Nomor')->searchable(),TextColumn::make('full_name')->label('Nama')->searchable(),TextColumn::make('period.name')->label('Periode'),TextColumn::make('email')->label('Surel'),TextColumn::make('selection_score')->label('Nilai Seleksi'),TextColumn::make('status')->label('Status')->badge(),TextColumn::make('submitted_at')->label('Diajukan Pada')->dateTime('d M Y H:i')])->actions([EditAction::make()->label('Ubah')->visible(fn(Applicant $r)=>!in_array($r->status,['converted'],true)),DeleteAction::make()->label('Hapus')->visible(fn(Applicant $r)=>$r->status==='draft')->requiresConfirmation()]);} public static function getPages():array{return ['index'=>Pages\ListApplicants::route('/'),'create'=>Pages\CreateApplicant::route('/create'),'edit'=>Pages\EditApplicant::route('/{record}/edit')];}}
''')
w('AdmissionBills/AdmissionBillResource.php',r'''<?php
namespace App\Filament\Resources\AdmissionBills;
use App\Models\AdmissionBill; use App\Filament\Resources\AdmissionBills\Pages; use Filament\Forms\Components\{DatePicker,Select,TextInput}; use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Support\Icons\Heroicon; use Filament\Tables\{Actions\DeleteAction,Actions\EditAction,Columns\TextColumn,Table}; use BackedEnum; use UnitEnum;
class AdmissionBillResource extends Resource { protected static ?string $slug='admission-bills'; protected static ?string $model=AdmissionBill::class; protected static string|BackedEnum|null $navigationIcon=Heroicon::OutlinedDocumentCurrencyDollar; protected static string|UnitEnum|null $navigationGroup='Penerimaan Mahasiswa Baru'; protected static ?string $navigationLabel='Tagihan PMB'; protected static ?string $modelLabel='Tagihan PMB'; protected static ?string $pluralModelLabel='Tagihan PMB'; public static function form(Schema $schema):Schema{return $schema->components([Select::make('applicant_id')->label('Pendaftar')->relationship('applicant','registration_number')->searchable()->preload()->required(),Select::make('fee_type_id')->label('Jenis Biaya')->relationship('feeType','name')->searchable()->preload(),TextInput::make('bill_number')->label('Nomor Tagihan')->required()->maxLength(80),TextInput::make('purpose')->label('Keperluan')->required()->maxLength(40),DatePicker::make('issued_at')->label('Diterbitkan Pada')->required(),DatePicker::make('due_date')->label('Jatuh Tempo')->required(),TextInput::make('amount')->label('Nominal')->numeric()->minValue(0)->required(),TextInput::make('paid_amount')->label('Terbayar')->numeric()->minValue(0)->default(0),Select::make('status')->label('Status')->options(['unpaid'=>'Belum Bayar','partial'=>'Sebagian','paid'=>'Lunas','overdue'=>'Jatuh Tempo'])->default('unpaid')->required()]);} public static function table(Table $table):Table{return $table->columns([TextColumn::make('bill_number')->label('Nomor'),TextColumn::make('applicant.registration_number')->label('Pendaftar'),TextColumn::make('amount')->label('Nominal')->money('IDR'),TextColumn::make('paid_amount')->label('Terbayar')->money('IDR'),TextColumn::make('status')->label('Status')->badge(),TextColumn::make('due_date')->label('Jatuh Tempo')->date()])->actions([EditAction::make()->label('Ubah')->visible(fn(AdmissionBill $r)=>$r->status!=='paid'),DeleteAction::make()->label('Hapus')->visible(fn(AdmissionBill $r)=>$r->paid_amount==0)->requiresConfirmation()]);} public static function getPages():array{return ['index'=>Pages\ListAdmissionBills::route('/'),'create'=>Pages\CreateAdmissionBill::route('/create'),'edit'=>Pages\EditAdmissionBill::route('/{record}/edit')];}}
''')
w('AdmissionPayments/AdmissionPaymentResource.php',r'''<?php
namespace App\Filament\Resources\AdmissionPayments;
use App\Models\AdmissionPayment; use App\Filament\Resources\AdmissionPayments\Pages; use Filament\Forms\Components\{DateTimePicker,Select,TextInput}; use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Support\Icons\Heroicon; use Filament\Tables\{Actions\DeleteAction,Actions\EditAction,Columns\TextColumn,Table}; use BackedEnum; use UnitEnum;
class AdmissionPaymentResource extends Resource { protected static ?string $slug='admission-payments'; protected static ?string $model=AdmissionPayment::class; protected static string|BackedEnum|null $navigationIcon=Heroicon::OutlinedCreditCard; protected static string|UnitEnum|null $navigationGroup='Penerimaan Mahasiswa Baru'; protected static ?string $navigationLabel='Pembayaran PMB'; protected static ?string $modelLabel='Pembayaran PMB'; protected static ?string $pluralModelLabel='Pembayaran PMB'; public static function form(Schema $schema):Schema{return $schema->components([Select::make('admission_bill_id')->label('Tagihan PMB')->relationship('bill','bill_number')->searchable()->preload()->required(),Select::make('applicant_id')->label('Pendaftar')->relationship('applicant','registration_number')->searchable()->preload()->required(),TextInput::make('payment_number')->label('Nomor Pembayaran')->required()->maxLength(80),TextInput::make('amount')->label('Nominal')->numeric()->minValue(0.01)->required(),Select::make('method')->label('Metode')->options(['cash'=>'Tunai','transfer'=>'Transfer','virtual_account'=>'Virtual Account','qris'=>'QRIS'])->required(),Select::make('status')->label('Status')->options(['pending'=>'Menunggu','confirmed'=>'Dikonfirmasi','failed'=>'Gagal','void'=>'Dibatalkan'])->default('confirmed')->required(),DateTimePicker::make('paid_at')->label('Dibayar Pada')->required(),TextInput::make('reference')->label('Referensi')->maxLength(150)]);} public static function table(Table $table):Table{return $table->columns([TextColumn::make('payment_number')->label('Nomor'),TextColumn::make('bill.bill_number')->label('Tagihan'),TextColumn::make('applicant.registration_number')->label('Pendaftar'),TextColumn::make('amount')->label('Nominal')->money('IDR'),TextColumn::make('method')->label('Metode')->badge(),TextColumn::make('status')->label('Status')->badge(),TextColumn::make('paid_at')->label('Waktu')->dateTime('d M Y H:i')])->actions([EditAction::make()->label('Ubah')->visible(fn(AdmissionPayment $r)=>$r->status==='pending'),DeleteAction::make()->label('Hapus')->visible(fn(AdmissionPayment $r)=>$r->status==='pending')->requiresConfirmation()]);} public static function getPages():array{return ['index'=>Pages\ListAdmissionPayments::route('/'),'create'=>Pages\CreateAdmissionPayment::route('/create'),'edit'=>Pages\EditAdmissionPayment::route('/{record}/edit')];}}
''')
print('generated')
