from pathlib import Path
root=Path('/home/ubuntu/siakad-laravel/app/Filament/Resources')
def w(rel,s):
 p=root/rel;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(s.strip()+'\n')
w('AttendanceSessions/AttendanceSessionResource.php',r'''<?php
namespace App\Filament\Resources\AttendanceSessions;
use App\Models\AttendanceSession; use App\Filament\Resources\AttendanceSessions\Pages; use Filament\Forms\Components\{DatePicker,Select,TextInput}; use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Support\Icons\Heroicon; use Filament\Tables\{Actions\DeleteAction,Actions\EditAction,Columns\TextColumn,Table}; use BackedEnum; use UnitEnum;
class AttendanceSessionResource extends Resource { protected static ?string $slug='attendance-sessions'; protected static ?string $model=AttendanceSession::class; protected static string|BackedEnum|null $navigationIcon=Heroicon::OutlinedCalendarDays; protected static string|UnitEnum|null $navigationGroup='Presensi'; protected static ?string $navigationLabel='Sesi Presensi'; protected static ?string $modelLabel='Sesi Presensi'; protected static ?string $pluralModelLabel='Sesi Presensi'; public static function form(Schema $schema):Schema{return $schema->components([Select::make('course_class_id')->label('Kelas Perkuliahan')->relationship('courseClass','class_code')->searchable()->preload()->required(),DatePicker::make('meeting_date')->label('Tanggal Pertemuan')->required()->native(false),TextInput::make('meeting_number')->label('Pertemuan Ke-')->numeric()->minValue(1)->maxValue(32)->required(),TextInput::make('topic')->label('Topik')->maxLength(255)]);} public static function table(Table $table):Table{return $table->columns([TextColumn::make('courseClass.class_code')->label('Kelas'),TextColumn::make('courseClass.course.name')->label('Mata Kuliah'),TextColumn::make('meeting_date')->label('Tanggal')->date('d M Y'),TextColumn::make('meeting_number')->label('Pertemuan Ke-')->sortable(),TextColumn::make('topic')->label('Topik')->searchable(),TextColumn::make('opened_at')->label('Dibuka')->dateTime('d M Y H:i'),TextColumn::make('closed_at')->label('Ditutup')->dateTime('d M Y H:i')])->actions([EditAction::make()->label('Ubah')->visible(fn(AttendanceSession $r)=>$r->closed_at===null),DeleteAction::make()->label('Hapus')->visible(fn(AttendanceSession $r)=>$r->opened_at===null)->requiresConfirmation()]);} public static function getPages():array{return ['index'=>Pages\ListAttendanceSessions::route('/'),'create'=>Pages\CreateAttendanceSession::route('/create'),'edit'=>Pages\EditAttendanceSession::route('/{record}/edit')];}}
''')
w('AttendanceRecords/AttendanceRecordResource.php',r'''<?php
namespace App\Filament\Resources\AttendanceRecords;
use App\Models\AttendanceRecord; use App\Filament\Resources\AttendanceRecords\Pages; use Filament\Forms\Components\{DateTimePicker,Select,Textarea}; use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Support\Icons\Heroicon; use Filament\Tables\{Actions\DeleteAction,Actions\EditAction,Columns\TextColumn,Table}; use BackedEnum; use UnitEnum;
class AttendanceRecordResource extends Resource { protected static ?string $slug='attendance-records'; protected static ?string $model=AttendanceRecord::class; protected static string|BackedEnum|null $navigationIcon=Heroicon::OutlinedCheckCircle; protected static string|UnitEnum|null $navigationGroup='Presensi'; protected static ?string $navigationLabel='Rekaman Presensi'; protected static ?string $modelLabel='Rekaman Presensi'; protected static ?string $pluralModelLabel='Rekaman Presensi'; public static function form(Schema $schema):Schema{return $schema->components([Select::make('attendance_session_id')->label('Sesi Presensi')->relationship('session','meeting_date')->searchable()->preload()->required(),Select::make('student_id')->label('Mahasiswa')->relationship('student','nim')->searchable()->preload()->required(),Select::make('status')->label('Status Kehadiran')->options(['present'=>'Hadir','late'=>'Terlambat','absent'=>'Tidak Hadir','excused'=>'Izin'])->default('present')->required(),DateTimePicker::make('check_in_at')->label('Waktu Check-in')->native(false),Textarea::make('notes')->label('Catatan')->columnSpanFull()]);} public static function table(Table $table):Table{return $table->columns([TextColumn::make('session.courseClass.class_code')->label('Kelas'),TextColumn::make('session.meeting_date')->label('Tanggal')->date(),TextColumn::make('student.nim')->label('NIM')->searchable(),TextColumn::make('student.user.name')->label('Mahasiswa')->searchable(),TextColumn::make('status')->label('Status')->badge(),TextColumn::make('check_in_at')->label('Check-in')->dateTime('d M Y H:i')])->actions([EditAction::make()->label('Ubah'),DeleteAction::make()->label('Hapus')->requiresConfirmation()]);} public static function getPages():array{return ['index'=>Pages\ListAttendanceRecords::route('/'),'create'=>Pages\CreateAttendanceRecord::route('/create'),'edit'=>Pages\EditAttendanceRecord::route('/{record}/edit')];}}
''')
w('AttendanceCorrections/AttendanceCorrectionResource.php',r'''<?php
namespace App\Filament\Resources\AttendanceCorrections;
use App\Models\AttendanceCorrection; use App\Filament\Resources\AttendanceCorrections\Pages; use Filament\Forms\Components\{Select,Textarea}; use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Support\Icons\Heroicon; use Filament\Tables\{Actions\DeleteAction,Actions\EditAction,Columns\TextColumn,Table}; use BackedEnum; use UnitEnum;
class AttendanceCorrectionResource extends Resource { protected static ?string $slug='attendance-corrections'; protected static ?string $model=AttendanceCorrection::class; protected static string|BackedEnum|null $navigationIcon=Heroicon::OutlinedPencilSquare; protected static string|UnitEnum|null $navigationGroup='Presensi'; protected static ?string $navigationLabel='Koreksi Presensi'; protected static ?string $modelLabel='Koreksi Presensi'; protected static ?string $pluralModelLabel='Koreksi Presensi'; public static function form(Schema $schema):Schema{return $schema->components([Select::make('attendance_record_id')->label('Rekaman Presensi')->relationship('attendanceRecord','id')->searchable()->preload()->required(),Select::make('requested_by')->label('Diajukan Oleh')->relationship('requestedBy','name')->searchable()->preload()->required(),Textarea::make('reason')->label('Alasan Koreksi')->required()->columnSpanFull(),Select::make('status')->label('Status')->options(['pending'=>'Menunggu','approved'=>'Disetujui','rejected'=>'Ditolak'])->default('pending')->required(),Select::make('approved_by')->label('Disetujui Oleh')->relationship('approvedBy','name')->searchable()->preload()->nullable()]);} public static function table(Table $table):Table{return $table->columns([TextColumn::make('attendanceRecord.student.nim')->label('NIM'),TextColumn::make('requestedBy.name')->label('Pengaju'),TextColumn::make('reason')->label('Alasan')->limit(50),TextColumn::make('status')->label('Status')->badge(),TextColumn::make('approvedBy.name')->label('Penyetuju')->placeholder('-')])->actions([EditAction::make()->label('Ubah')->visible(fn(AttendanceCorrection $r)=>$r->status==='pending'),DeleteAction::make()->label('Hapus')->visible(fn(AttendanceCorrection $r)=>$r->status==='pending')->requiresConfirmation()]);} public static function getPages():array{return ['index'=>Pages\ListAttendanceCorrections::route('/'),'create'=>Pages\CreateAttendanceCorrection::route('/create'),'edit'=>Pages\EditAttendanceCorrection::route('/{record}/edit')];}}
''')
w('Assessments/AssessmentResource.php',r'''<?php
namespace App\Filament\Resources\Assessments;
use App\Models\Assessment; use App\Filament\Resources\Assessments\Pages; use Filament\Forms\Components\{Select,TextInput}; use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Support\Icons\Heroicon; use Filament\Tables\{Actions\DeleteAction,Actions\EditAction,Columns\TextColumn,Table}; use BackedEnum; use UnitEnum;
class AssessmentResource extends Resource { protected static ?string $slug='assessments'; protected static ?string $model=Assessment::class; protected static string|BackedEnum|null $navigationIcon=Heroicon::OutlinedClipboardDocumentCheck; protected static string|UnitEnum|null $navigationGroup='Penilaian'; protected static ?string $navigationLabel='Komponen Penilaian'; protected static ?string $modelLabel='Komponen Penilaian'; protected static ?string $pluralModelLabel='Komponen Penilaian'; public static function form(Schema $schema):Schema{return $schema->components([Select::make('course_class_id')->label('Kelas')->relationship('courseClass','class_code')->searchable()->preload()->required(),TextInput::make('name')->label('Nama Komponen')->required()->maxLength(100),TextInput::make('weight')->label('Bobot (%)')->numeric()->minValue(0)->maxValue(100)->required(),TextInput::make('max_score')->label('Nilai Maksimal')->numeric()->minValue(1)->default(100)->required()]);} public static function table(Table $table):Table{return $table->columns([TextColumn::make('courseClass.class_code')->label('Kelas'),TextColumn::make('name')->label('Komponen')->searchable(),TextColumn::make('weight')->label('Bobot (%)'),TextColumn::make('max_score')->label('Nilai Maksimal')])->actions([EditAction::make()->label('Ubah'),DeleteAction::make()->label('Hapus')->requiresConfirmation()]);} public static function getPages():array{return ['index'=>Pages\ListAssessments::route('/'),'create'=>Pages\CreateAssessment::route('/create'),'edit'=>Pages\EditAssessment::route('/{record}/edit')];}}
''')
w('StudentGrades/StudentGradeResource.php',r'''<?php
namespace App\Filament\Resources\StudentGrades;
use App\Models\StudentGrade; use App\Filament\Resources\StudentGrades\Pages; use Filament\Forms\Components\{Select,TextInput}; use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Support\Icons\Heroicon; use Filament\Tables\{Actions\DeleteAction,Actions\EditAction,Columns\TextColumn,Table}; use BackedEnum; use UnitEnum;
class StudentGradeResource extends Resource { protected static ?string $slug='student-grades'; protected static ?string $model=StudentGrade::class; protected static string|BackedEnum|null $navigationIcon=Heroicon::OutlinedAcademicCap; protected static string|UnitEnum|null $navigationGroup='Penilaian'; protected static ?string $navigationLabel='Nilai Mahasiswa'; protected static ?string $modelLabel='Nilai Mahasiswa'; protected static ?string $pluralModelLabel='Nilai Mahasiswa'; public static function form(Schema $schema):Schema{return $schema->components([Select::make('course_class_id')->label('Kelas')->relationship('courseClass','class_code')->searchable()->preload()->required(),Select::make('student_id')->label('Mahasiswa')->relationship('student','nim')->searchable()->preload()->required(),Select::make('assessment_id')->label('Komponen')->relationship('assessment','name')->searchable()->preload()->required(),TextInput::make('score')->label('Nilai')->numeric()->minValue(0)->maxValue(100),TextInput::make('letter_grade')->label('Nilai Huruf')->maxLength(5),Select::make('graded_by')->label('Dinilai Oleh')->relationship('gradedBy','name')->searchable()->preload()->nullable()]);} public static function table(Table $table):Table{return $table->columns([TextColumn::make('courseClass.class_code')->label('Kelas'),TextColumn::make('student.nim')->label('NIM'),TextColumn::make('student.user.name')->label('Mahasiswa'),TextColumn::make('assessment.name')->label('Komponen'),TextColumn::make('score')->label('Nilai'),TextColumn::make('letter_grade')->label('Nilai Huruf')])->actions([EditAction::make()->label('Ubah'),DeleteAction::make()->label('Hapus')->requiresConfirmation()]);} public static function getPages():array{return ['index'=>Pages\ListStudentGrades::route('/'),'create'=>Pages\CreateStudentGrade::route('/create'),'edit'=>Pages\EditStudentGrade::route('/{record}/edit')];}}
''')
w('GradeSubmissions/GradeSubmissionResource.php',r'''<?php
namespace App\Filament\Resources\GradeSubmissions;
use App\Models\GradeSubmission; use App\Filament\Resources\GradeSubmissions\Pages; use Filament\Forms\Components\{DateTimePicker,Select}; use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Support\Icons\Heroicon; use Filament\Tables\{Actions\DeleteAction,Actions\EditAction,Columns\TextColumn,Table}; use BackedEnum; use UnitEnum;
class GradeSubmissionResource extends Resource { protected static ?string $slug='grade-submissions'; protected static ?string $model=GradeSubmission::class; protected static string|BackedEnum|null $navigationIcon=Heroicon::OutlinedPaperAirplane; protected static string|UnitEnum|null $navigationGroup='Penilaian'; protected static ?string $navigationLabel='Pengajuan Nilai'; protected static ?string $modelLabel='Pengajuan Nilai'; protected static ?string $pluralModelLabel='Pengajuan Nilai'; public static function form(Schema $schema):Schema{return $schema->components([Select::make('course_class_id')->label('Kelas')->relationship('courseClass','class_code')->searchable()->preload()->required(),Select::make('submitted_by')->label('Diajukan Oleh')->relationship('submittedBy','name')->searchable()->preload()->required(),Select::make('status')->label('Status')->options(['draft'=>'Draf','submitted'=>'Diajukan','approved'=>'Disetujui','published'=>'Dipublikasikan','rejected'=>'Ditolak'])->default('draft')->required(),DateTimePicker::make('submitted_at')->label('Diajukan Pada')->native(false),Select::make('approved_by')->label('Disetujui Oleh')->relationship('approvedBy','name')->searchable()->preload()->nullable()]);} public static function table(Table $table):Table{return $table->columns([TextColumn::make('courseClass.class_code')->label('Kelas'),TextColumn::make('submittedBy.name')->label('Pengaju'),TextColumn::make('status')->label('Status')->badge(),TextColumn::make('submitted_at')->label('Diajukan Pada')->dateTime('d M Y H:i'),TextColumn::make('approvedBy.name')->label('Penyetuju')->placeholder('-')])->actions([EditAction::make()->label('Ubah')->visible(fn(GradeSubmission $r)=>in_array($r->status,['draft','rejected'],true)),DeleteAction::make()->label('Hapus')->visible(fn(GradeSubmission $r)=>$r->status==='draft')->requiresConfirmation()]);} public static function getPages():array{return ['index'=>Pages\ListGradeSubmissions::route('/'),'create'=>Pages\CreateGradeSubmission::route('/create'),'edit'=>Pages\EditGradeSubmission::route('/{record}/edit')];}}
''')
print('generated')
