from pathlib import Path
root=Path('/home/ubuntu/siakad-laravel/app/Filament/Resources')
def write(rel,text):
 p=root/rel; p.parent.mkdir(parents=True,exist_ok=True); p.write_text(text.strip()+'\n')
write('Facultys/FacultyResource.php',r'''<?php
namespace App\Filament\Resources\Facultys;
use App\Models\Faculty; use App\Filament\Resources\Facultys\Pages; use Filament\Forms\Components\{Select,TextInput}; use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Support\Icons\Heroicon; use Filament\Tables\{Actions\DeleteAction,Actions\EditAction,Columns\TextColumn,Table}; use BackedEnum; use UnitEnum;
class FacultyResource extends Resource { protected static ?string $slug='faculties'; protected static ?string $model=Faculty::class; protected static string|BackedEnum|null $navigationIcon=Heroicon::OutlinedBuildingOffice; protected static string|UnitEnum|null $navigationGroup='Organisasi Akademik'; protected static ?string $navigationLabel='Fakultas'; protected static ?string $modelLabel='Fakultas'; protected static ?string $pluralModelLabel='Fakultas'; public static function form(Schema $schema):Schema{return $schema->components([TextInput::make('code')->label('Kode Fakultas')->required()->unique(ignoreRecord:true)->maxLength(30),TextInput::make('name')->label('Nama Fakultas')->required()->maxLength(255),Select::make('dean_id')->label('Dekan')->relationship('dean','nidn')->searchable()->preload()->nullable()]);} public static function table(Table $table):Table{return $table->columns([TextColumn::make('code')->label('Kode')->searchable()->sortable(),TextColumn::make('name')->label('Nama Fakultas')->searchable()->sortable(),TextColumn::make('dean.user.name')->label('Dekan')->placeholder('Belum ditetapkan'),TextColumn::make('departments_count')->label('Jumlah Departemen')->counts('departments')])->actions([EditAction::make()->label('Ubah'),DeleteAction::make()->label('Hapus')->requiresConfirmation()])->defaultSort('code');} public static function getPages():array{return ['index'=>Pages\ListFacultys::route('/'),'create'=>Pages\CreateFaculty::route('/create'),'edit'=>Pages\EditFaculty::route('/{record}/edit')];}}
''')
write('Departments/DepartmentResource.php',r'''<?php
namespace App\Filament\Resources\Departments;
use App\Models\Department; use App\Filament\Resources\Departments\Pages; use Filament\Forms\Components\{Select,TextInput}; use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Support\Icons\Heroicon; use Filament\Tables\{Actions\DeleteAction,Actions\EditAction,Columns\TextColumn,Table}; use BackedEnum; use UnitEnum;
class DepartmentResource extends Resource { protected static ?string $slug='departments'; protected static ?string $model=Department::class; protected static string|BackedEnum|null $navigationIcon=Heroicon::OutlinedBuildingOffice2; protected static string|UnitEnum|null $navigationGroup='Organisasi Akademik'; protected static ?string $navigationLabel='Departemen'; protected static ?string $modelLabel='Departemen'; protected static ?string $pluralModelLabel='Departemen'; public static function form(Schema $schema):Schema{return $schema->components([Select::make('faculty_id')->label('Fakultas')->relationship('faculty','name')->searchable()->preload()->required(),TextInput::make('code')->label('Kode Departemen')->required()->unique(ignoreRecord:true)->maxLength(30),TextInput::make('name')->label('Nama Departemen')->required()->maxLength(255),Select::make('head_of_dept_id')->label('Ketua Departemen')->relationship('headOfDepartment','nidn')->searchable()->preload()->nullable()]);} public static function table(Table $table):Table{return $table->columns([TextColumn::make('faculty.name')->label('Fakultas')->searchable(),TextColumn::make('code')->label('Kode')->searchable()->sortable(),TextColumn::make('name')->label('Nama Departemen')->searchable()->sortable(),TextColumn::make('headOfDepartment.user.name')->label('Ketua Departemen')->placeholder('Belum ditetapkan'),TextColumn::make('study_programs_count')->label('Jumlah Program Studi')->counts('studyPrograms')])->actions([EditAction::make()->label('Ubah'),DeleteAction::make()->label('Hapus')->requiresConfirmation()])->defaultSort('code');} public static function getPages():array{return ['index'=>Pages\ListDepartments::route('/'),'create'=>Pages\CreateDepartment::route('/create'),'edit'=>Pages\EditDepartment::route('/{record}/edit')];}}
''')
write('StudyPrograms/StudyProgramResource.php',r'''<?php
namespace App\Filament\Resources\StudyPrograms;
use App\Models\StudyProgram; use App\Filament\Resources\StudyPrograms\Pages; use Filament\Forms\Components\{Select,TextInput}; use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Support\Icons\Heroicon; use Filament\Tables\{Actions\DeleteAction,Actions\EditAction,Columns\TextColumn,Table}; use BackedEnum; use UnitEnum;
class StudyProgramResource extends Resource { protected static ?string $slug='study-programs'; protected static ?string $model=StudyProgram::class; protected static string|BackedEnum|null $navigationIcon=Heroicon::OutlinedAcademicCap; protected static string|UnitEnum|null $navigationGroup='Organisasi Akademik'; protected static ?string $navigationLabel='Program Studi'; protected static ?string $modelLabel='Program Studi'; protected static ?string $pluralModelLabel='Program Studi'; public static function form(Schema $schema):Schema{return $schema->components([Select::make('department_id')->label('Departemen')->relationship('department','name')->searchable()->preload()->required(),TextInput::make('code')->label('Kode Program Studi')->required()->unique(ignoreRecord:true)->maxLength(30),TextInput::make('name')->label('Nama Program Studi')->required()->maxLength(255),Select::make('level')->label('Jenjang')->options(['D3'=>'Diploma 3','D4'=>'Diploma 4','S1'=>'Sarjana','S2'=>'Magister','S3'=>'Doktor'])->nullable(),Select::make('accreditation')->label('Akreditasi')->options(['Unggul'=>'Unggul','Baik Sekali'=>'Baik Sekali','Baik'=>'Baik','Tidak Terakreditasi'=>'Tidak Terakreditasi'])->nullable(),Select::make('head_of_program_id')->label('Ketua Program Studi')->relationship('headOfProgram','nidn')->searchable()->preload()->nullable()]);} public static function table(Table $table):Table{return $table->columns([TextColumn::make('department.faculty.name')->label('Fakultas')->searchable(),TextColumn::make('department.name')->label('Departemen')->searchable(),TextColumn::make('code')->label('Kode')->searchable()->sortable(),TextColumn::make('name')->label('Nama Program Studi')->searchable()->sortable(),TextColumn::make('level')->label('Jenjang')->badge(),TextColumn::make('accreditation')->label('Akreditasi')->badge(),TextColumn::make('headOfProgram.user.name')->label('Ketua Program Studi')->placeholder('Belum ditetapkan')])->actions([EditAction::make()->label('Ubah'),DeleteAction::make()->label('Hapus')->requiresConfirmation()])->defaultSort('code');} public static function getPages():array{return ['index'=>Pages\ListStudyPrograms::route('/'),'create'=>Pages\CreateStudyProgram::route('/create'),'edit'=>Pages\EditStudyProgram::route('/{record}/edit')];}}
''')
print('generated')
